name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag crud-app:$(date +%s)
      
      env:
        latest_image: docker images | awk '{print $2}' | awk 'NR==2'

    - name: Echo another task
      run: $latest_image