name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag crud-app:$(date +%s)
      
      env:
        latest_image: docker images | awk '{print $3}' | awk 'NR==2'

    - name: Run the Docker container using above key
      run: docker run -it -p 8080:9000 crud-app:$latest_image

    - name: Echo a single world
      run: echo hello
