name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ununtu-latest

    steps:
    - uses: actions/checkout@v2
    
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag crud-app:$(date +%s)
    - name: Docker Build & Push to Docker Hub
      uses: opspresso/action-docker@master
      with:
          args: --docker
      env:
        USERNAME: "kkjamdagni"
        PASSWORD: "alfa123123"
        DOCKERFILE: "Dockerfile"
        IMAGE_NAME: "kkjamdagni/crud-app"
        TAG_NAME: "v0.0.1"
        LATEST: "true"
